cloud:
  aws:
    credentials:
      useDefaultAwsCredentialsChain: false
      profileName: yokoikzk-app-user
      instanceProfile: false
    stack:
      auto: false
    region:
      auto: false
      static: ap-northeast-1
service:
  user:
    dns: http://localhost:8081
  message:
    dns: http://localhost:8082
server:
  port: 8082
